IA-1302 IA-1308 test new R kernel image
DataBiosphere/leonardo pull request #1044
Opened 2019-08-26 19:42 UTC by Qi77Qi

https://broadworkbench.atlassian.net/browse/IA-1302

superseded by https://github.com/DataBiosphere/leonardo/pull/1045
\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2019-08-26 20:58 UTC, Qi77Qi commented
jenkins test

2019-08-27 20:12 UTC, Qi77Qi commented
jenkins retest

2019-08-27 21:27 UTC, rtitle commented on automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/notebooks/NotebookRKernelSpec.scala
> +  override val jupyterDockerImage: Option[String] = Some("us.gcr.io/broad-dsp-gcr-public/terra-jupyter-r:0.0.1")
Just curious if this should read from a conf file or something... when we update the R image we'll need to update this line. Not a blocker for this PR.

2019-08-27 21:32 UTC, rtitle commented on src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala
> +      _ <- removeIamRolesForUser
Just reading the code, I'm not sure we need the `removeIamRolesForUser` method anymore. Can we get rid of `removeIamRolesForUser` and just call `clusterHelper.removeClusterIamRoles()` directly here?

The existing code did some checking to make sure we don't prematurely remove roles if the user has some Creating clusters. I don't think we need that if doing it at deletion time -- ClusterHelper should take care of all the logic.

2019-08-27 21:33 UTC, rtitle requested changes
Just 1 request for the IAM stuff, see above.

Also it seems a test failed: `NotebookRKernelSpec should be able to install mlr`

2019-08-27 21:48 UTC, Qi77Qi commented on automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/notebooks/NotebookRKernelSpec.scala
> +  override val jupyterDockerImage: Option[String] = Some("us.gcr.io/broad-dsp-gcr-public/terra-jupyter-r:0.0.1")
yea, I was just being lazy especially build has worked yet :)

2019-08-28 16:04 UTC, Qi77Qi commented
clusterMonitorSpec seems to pass locally..jenkins retest

2019-08-29 00:06 UTC, Qi77Qi commented
jenkins retest

2019-08-29 15:06 UTC, rtitle approved these changes
This looks good, odd tests are failing. I'm actually deploying this branch to a fiab to see if the preemptibles error is fixed.

2019-08-29 15:11 UTC, rtitle commented
jenkins retest

2019-08-29 15:44 UTC, rtitle commented
@Qi77Qi in my fiab (running Terra) I am able to pause/resume clusters with preemptibles, and also add/remove preemptibles on a cluster. It _feels_ like the issue is fixed. Let's see how this test run does.

2019-08-29 15:58 UTC, rtitle commented
It failed again... I think I have a theory why. Gonna try 1 more change.

2019-08-29 16:29 UTC, rtitle commented
I broke out my idea into a new PR: https://github.com/DataBiosphere/leonardo/pull/1045/

Haven't done much testing yet, will iterate.

2019-08-29 17:54 UTC, closed without merging