python3 image incorporated into tests and all are passing
DataBiosphere/leonardo pull request #1047
Opened 2019-08-29 19:16 UTC by jdcanas

Removing python2 and spark (temporarily) from tests.

All tests for python3 are passing now, with the python3 image.

It may be worth adding an explicit test for each package we import.

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2019-08-29 19:17 UTC, Qi77Qi approved these changes
:shipit:

2019-08-29 19:53 UTC, Qi77Qi requested changes
actually, I think image name should be renamed to `terra-jupyter-python`

2019-08-30 18:17 UTC, rtitle approved these changes
+1 to `terra-jupyter-python` (since this is the Jupyter stack).

Otherwise looks good.

2019-09-03 19:51 UTC, Qi77Qi commented
jenkins retest

2019-09-03 20:50 UTC, Qi77Qi commented
I refactored the directory name

2019-09-03 20:50 UTC, merged