Support aou Leo image in GCE workflow
DataBiosphere/leonardo pull request #1308
Opened 2020-03-04 19:54 UTC by calbach

Sister PR to DataBiosphere/terra-docker#106

Reopened with different branch name from https://github.com/DataBiosphere/leonardo/pull/1307

CC @kyuksel @jdcanas 

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2020-03-04 20:58 UTC, calbach commented
:( 
![image](https://user-images.githubusercontent.com/822298/75922437-ddffa980-5e17-11ea-9846-5313f059432d.png)

2020-03-04 21:06 UTC, kyuksel requested changes
Looks good. Mentioned inline a missing update.

2020-03-04 21:06 UTC, kyuksel commented on jenkins/gce-custom-images/prepare_custom_leonardo_gce_image.sh
> +docker_image_var_names="welder_server leonardo_jupyter terra_jupyter_base terra_jupyter_python terra_jupyter_r terra_jupyter_bioconductor terra_jupyter_gatk terra_jupyter_aou openidc_proxy anvil_rstu
The two lines added to this file also need to be added to `prepare-custom-leonardo-jupyter-dataproc-image.sh`.

2020-03-04 22:37 UTC, calbach commented on jenkins/gce-custom-images/prepare_custom_leonardo_gce_image.sh
> +docker_image_var_names="welder_server leonardo_jupyter terra_jupyter_base terra_jupyter_python terra_jupyter_r terra_jupyter_bioconductor terra_jupyter_gatk terra_jupyter_aou openidc_proxy anvil_rstu
Oops sorry - I missed this comment on the previous attempt. Added

2020-03-04 23:06 UTC, kyuksel approved these changes
👍 pending tests passing

2020-03-04 23:39 UTC, rtitle commented on automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoConfig.scala
> +    val aouImageUrl: String = leonardo.getString("aouImageUrl")
There needs to be a corresponding entry here: https://github.com/DataBiosphere/leonardo/blob/develop/automation/src/test/resources/reference.conf

2020-03-04 23:59 UTC, rtitle approved these changes
:shipit: if the test passes

2020-03-05 00:53 UTC, rtitle commented on automation/src/test/resources/reference.conf
> +leonardo.gatkImageUrl = "us.gcr.io/broad-dsp-gcr-public/terra-jupyter-aou:0.0.1"
Typo, `leonardo.aouImageUrl`

2020-03-05 01:10 UTC, calbach commented on automation/src/test/resources/reference.conf
> +leonardo.gatkImageUrl = "us.gcr.io/broad-dsp-gcr-public/terra-jupyter-aou:0.0.1"
:man_facepalming:

2020-03-05 02:06 UTC, Qi77Qi commented on automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/notebooks/NotebookAouSpec.scala
> +class NotebookAouSpec extends ClusterFixtureSpec with NotebookTestUtils {
test needs to be added https://github.com/DataBiosphere/leonardo/blob/develop/automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSuite.scala#L93

2020-03-05 02:07 UTC, Qi77Qi requested changes
looks good once automation test if fixed

2020-03-05 15:30 UTC, rtitle commented
@Qi77Qi I committed a test fix and they passed :)

2020-03-05 15:30 UTC, Qi77Qi approved these changes

2020-03-05 15:30 UTC, merged