IA-1777 use different encoder for responses
DataBiosphere/leonardo pull request #1333
Opened 2020-03-23 23:11 UTC by Qi77Qi

https://broadworkbench.atlassian.net/browse/IA-1777

Use different encoder for `GetRuntimeResponse` and `ListRuntimeResponse` in runtime routes so that we're not returning fields like `clusterName`.

What's in swagger doc is not a complete list of what we return currently. It should be easy to add those additional fields if we need to.

for `dataprocInstances` field previously returned in `getClusterResponse`, I'm leaving it out in new route's encoder because I'd like to refactor `Instance` table to reference `RuntimeConfig` table instead of `Cluster`. And we can add `dataprocInstances` in `runtimeConfig` field once that's done.

---
Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; Delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2020-03-24 12:58 UTC, rtitle commented on http/src/main/resources/swagger/api-docs.yaml
> +          description: The internally-referenced ID of the cluster
Maybe let's s/cluster/runtime in the descriptions?

2020-03-24 12:59 UTC, rtitle commented on http/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/RuntimeRoutes.scala
> +  //TODO: add `dataprocInstances` when it's added to `RuntimeConfig` https://broadworkbench.atlassian.net/browse/IA-1778
Agreed `dataprocInstances` makes sense in `RuntimeConfig`. Will need to do a DB migration.

2020-03-24 13:00 UTC, rtitle commented on http/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/RuntimeRoutes.scala
> +  //TODO: add `dataprocInstances` when it's added to `RuntimeConfig` https://broadworkbench.atlassian.net/browse/IA-1778
As far as I know clients don't use this field, so should be fine to leave it out for now.

2020-03-24 13:00 UTC, rtitle requested changes
1 swagger change requested; plus CI is failing

2020-03-24 22:38 UTC, Qi77Qi commented
@rtitle I addressed the comment. Let me know if you have more comments

2020-03-25 12:47 UTC, rtitle approved these changes

2020-03-25 13:00 UTC, merged