Update cromwell-runner-app version to 0.16.0
DataBiosphere/leonardo pull request #3633
Opened 2023-08-24 19:03 UTC by broadbot

This PR is auto-generated by
[terra-helmfile actions/make_leo_pr](https://github.com/broadinstitute/terra-helmfile/blob/main/.github/workflows/make_leo_pr.yml), using
[github actions/github-script](https://github.com/actions/github-script).

It updates cromwell-runner-app from chart version  to 0.16.0.

2023-08-24 19:08 UTC, dillydally414 requested changes
Argh. Not sure why it worked for WDS and not the Cromwell apps

2023-08-24 19:09 UTC, dillydally414 commented
#3632 worked as expected! Likely something cromwell-runner-app specific...

2023-08-25 15:21 UTC, dillydally414 approved these changes

2023-08-28 14:39 UTC, kpierre13 commented
jenkins retest

2023-08-28 19:19 UTC, merged