[IA-4626] naive defense vs SQL injection: forbid single quotes in params
DataBiosphere/leonardo pull request #4062
Opened 2023-12-14 21:19 UTC by mlilynolting

__Jira ticket__: https://broadworkbench.atlassian.net/browse/IA-4626

## Summary of changes

Quick and dirty patch to SQL hole in RuntimeV2Service: forbid single quotes in the label parameters' key-value pairs.

## Testing these changes

### What to test

- Try submitting requests with single quotes in label fields
- Try submitting requests in general to assert no regression issues

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

2023-12-15 16:19 UTC, TomConner requested changes
Bind variables would provide more protection. Can you look at using bind variables as suggested in this comment?

https://broadworkbench.atlassian.net/browse/IA-4626?focusedCommentId=85830

Happy to help sort this out!

2023-12-15 16:22 UTC, mlilynolting commented
@TomConner I plan to convert this query to an appropriately parameterized one to make it truly secure. Wanted to get this messy fix up so we had the option of merging sooner and improving later.

2023-12-15 16:44 UTC, TomConner approved these changes
Approving this because it does provide some value. but hoping for bind variables ASAP.

2023-12-15 21:33 UTC, lucymcnatt commented on http/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/http/service/RuntimeServiceInterp.scala
> +      )
This changes the behavior for runtimes, I think label maps are used in disks and apps as well, should we add similar logic to those services?

2023-12-15 21:34 UTC, lucymcnatt commented on http/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/http/service/RuntimeServiceInterp.scala
> +      )
that might be out of the scope of this particular ticket, but wanted to bring it up

2023-12-18 14:16 UTC, cindy-broadinstitute approved these changes

2023-12-18 16:35 UTC, mlilynolting commented
jenkins retest

2023-12-18 18:37 UTC, mlilynolting commented
Merging through known automation test flakes (RStudioSpec, RKernelSpec)

2023-12-18 18:37 UTC, merged