[IA-4767] Remove legacy aou docker image
DataBiosphere/leonardo pull request #4086
Opened 2024-01-04 12:45 UTC by LizBaldo

__Jira ticket__: https://broadworkbench.atlassian.net/browse/IA-4767

## Summary of changes

### What

-

### Why

-

## Testing these changes

### What to test

- 

### Who tested and where

- [ ] This change is covered by automated tests 
  - _NB: Rerun automation tests on this PR by commenting `jenkins retest` or `jenkins multi-test`._
- [ ] I validated this change 
- [ ] Primary reviewer validated this change 
- [ ] I validated this change in the dev environment

2024-01-04 14:10 UTC, Qi77Qi requested changes
great cleanup! one issue I commented on

2024-01-04 14:10 UTC, Qi77Qi commented on http/src/main/resources/reference.conf
> -  customGceImage = "projects/broad-dsp-gcr-public/global/images/leo-gce-image-2023-12-01-17-29-26"
you even generated new VM images? :)

2024-01-04 14:10 UTC, Qi77Qi commented on jenkins/dataproc-custom-images/prepare-custom-leonardo-jupyter-dataproc-image.sh
> -terra_jupyter_aou_old="us.gcr.io/broad-dsp-gcr-public/terra-jupyter-aou:2.1.15"
I think we still want this one...and update it to `2.2.7`

2024-01-04 14:10 UTC, Qi77Qi commented on jenkins/gce-custom-images/prepare_gce_image.sh
> -docker_image_var_names="welder_server terra_jupyter_python terra_jupyter_r terra_jupyter_bioconductor terra_jupyter_gatk terra_jupyter_aou terra_jupyter_aou_old openidc_proxy anvil_rstudio_bioconduct
we still need to cache "old". we just need to update "old" to be `2.2.7`

2024-01-04 14:45 UTC, Qi77Qi approved these changes
:shipit: 🎉

2024-01-04 15:44 UTC, LizBaldo commented on http/src/main/resources/reference.conf
> -  customGceImage = "projects/broad-dsp-gcr-public/global/images/leo-gce-image-2023-12-01-17-29-26"
Yeah I was a bit trigger happy, but the latest ones I generated have both aou images on it 👍

2024-01-05 14:30 UTC, LizBaldo commented
jenkins retest

2024-01-05 15:06 UTC, LizBaldo commented
jenkins retest

2024-01-05 16:44 UTC, LizBaldo commented
jenkins retest

2024-01-05 17:01 UTC, LizBaldo commented
I tested on my BEE the couple of cases that failed on jenkins and it works fine there, so if the job keeps failing I might force merge, because this is blocking AOU prod release correct @Qi77Qi?

2024-01-05 17:52 UTC, Qi77Qi commented
oh..this is not blocking AoU in ANY way...this PR is JUST for cleanup stuff in Leo

But I'm ok with force merging if failures look irrelevant

2024-01-05 21:42 UTC, lucymcnatt approved these changes

2024-01-08 14:19 UTC, LizBaldo commented
Oh okay, I thought AOU needed the 2.2.7 image cached, you don't need that for prod to run smoothly without runtime creation timeouts?

2024-01-08 16:08 UTC, LizBaldo commented
jenkins retest

2024-01-09 14:41 UTC, LizBaldo commented
jenkins retest

2024-01-09 18:50 UTC, LizBaldo commented
All tests did pass at one point, it's just flakiness so merging now

2024-01-09 18:59 UTC, Qi77Qi commented
2.2.7 is cached today? no?

2024-01-09 18:59 UTC, LizBaldo commented
It was not cached no, which is why I force merged this PR

2024-01-09 19:00 UTC, LizBaldo commented
2.2.8 was cached, and they are basically the same, so pulling it would be pretty fast anyways, but better cache it

2024-01-09 19:01 UTC, merged

2024-01-09 19:01 UTC, Qi77Qi commented
so what's cached today? 2.1.15 and what(I thought it's 2.2.7, which is why we upgraded to 2.2.7 in AoU)?

2024-01-09 19:01 UTC, LizBaldo commented
Today it's 2.1.15, and 2.2.8 (the latest), with this PR it's going to be 2.2.7 for prod and 2.2.8 for pre-prod