Apt-get cleanup
DataBiosphere/leonardo pull request #516
Opened 2018-07-30 23:36 UTC by vkumra-broad

\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2018-07-30 23:50 UTC, vkumra-broad commented
jenkins retest

2018-07-31 02:47 UTC, vkumra-broad commented
jenkins retest

2018-07-31 12:29 UTC, vkumra-broad commented
jenkins retest

2018-07-31 13:29 UTC, vkumra-broad commented
jenkins retest

2018-07-31 14:14 UTC, rtitle commented on jupyter-docker/Dockerfile
> + && apt-get clean \
I think this one should be in the previous layer? The previous one does the apt-gets, this one runs the `R install`s.

2018-07-31 14:15 UTC, rtitle requested changes
1 of them is in the wrong place - otherwise looks good, shaving off ~100MB is definitely valuable.

2018-07-31 14:16 UTC, kyuksel commented on jupyter-docker/Dockerfile
> + && rm -rf /var/lib/apt/lists/*
I wonder if it makes sense to combine `apt-get clean && rm -rf /var/lib/apt/lists/*` into an alias like so:

```alias apt-get-cleanup='apt-get clean && rm -rf /var/lib/apt/lists/*'```

2018-07-31 16:18 UTC, rtitle commented
Could you post some size results for before and after this change? I checked out this branch and built the docker file and strangely the image size increased:
```
rtitle@~$ docker images
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
rt-apt-get-cleanup                                  latest              bc4e1fc765fb        29 minutes ago      2.61GB
```

This doesn't seem right so I'm wondering if I did something wrong..

2018-07-31 17:42 UTC, vkumra-broad commented
```
<none>                              <none>                    ce6758b189dc        46 seconds ago      2.72GB 
<none>                              <none>                    ec209351a67b        19 minutes ago      2.84GB
```

First one is with apt-get cleanup, second one is without it

2018-07-31 17:59 UTC, vkumra-broad commented
jenkins retest

2018-07-31 19:46 UTC, rtitle approved these changes

2018-08-01 14:07 UTC, merged