#625: Make Dataproc init script timeout configurable
DataBiosphere/leonardo pull request #628
Opened 2018-10-15 18:17 UTC by MatthewBemis

will go in after https://github.com/broadinstitute/firecloud-develop/pull/1393 and tests will fail until then

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2018-10-15 20:21 UTC, vkumra-broad approved these changes

2018-10-16 13:18 UTC, rtitle commented on src/main/resources/reference.conf
> +  defaultExecutionTimeout = "1800s"
Typesafe config can parse:
```
defaultExecutionTimeout = 30 minutes
```
We use this pattern elsewhere in the config file.

2018-10-16 13:33 UTC, rtitle requested changes
One change requested to represent it as a `FiniteDuration` in Leo code, and convert to a Google duration in `HttpGoogleDataprocDAO`.

2018-10-16 17:52 UTC, MatthewBemis commented
@rtitle ready for re-review. see the note i left atop `finiteDurationToGoogleDuration`. if you think it matters that it won't support fractional seconds, i can add that support

2018-10-16 23:29 UTC, rtitle approved these changes
Looks great! cc @abaumann FYI this PR ups the cluster initialization timeout to 30 mins by default.

Can we do a quick test to verify that this works?

1. Create a bash script which sleeps for ~15 minutes and add it to a bucket
2. Create a cluster, specifying the gs:// path to that script
3. Make sure the cluster creation succeeds

I think a manual test is fine in this case, as opposed to an automation test (which would increase test execution time).

2018-10-16 23:38 UTC, rtitle commented
PS - yeah I think second-granularity is fine.

2018-10-17 20:27 UTC, merged