whitelist is removed
DataBiosphere/leonardo pull request #958
Opened 2019-06-07 17:46 UTC by Qi77Qi

\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2019-06-07 17:48 UTC, akarukappadath approved these changes

2019-06-07 19:10 UTC, Qi77Qi commented
jenkins retest

2019-06-13 16:05 UTC, rtitle requested changes
Ah good catch, I must have missed those. I think there is code depending on these fields though.

2019-08-15 18:44 UTC, jdcanas commented
closing for now until we begin working on https://broadworkbench.atlassian.net/secure/RapidBoard.jspa?rapidView=35&projectKey=IA&view=planning&selectedIssue=IA-1035&search=whitelist

2019-08-15 18:44 UTC, closed without merging