Update work mount location to match Jupyter home
DataBiosphere/leonardo pull request #962
Opened 2019-06-11 22:20 UTC by calbach

AFAICT /usr/home/work was never used. This is the location where notebooks are stored by default for Jupyter.

@rtitle in case I'm missing something

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/leonardo/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've documented my API changes in Swagger

In all cases:

- [ ] Get a thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2019-06-12 15:21 UTC, jmthibault79 reviewed
This makes sense to me, but I also wonder if we're missing some context.  Was this actually doing anything?

2019-06-12 20:35 UTC, rtitle commented
I think this makes sense but we should run a spark job to make sure spark isn’t relying on this somehow

2019-06-12 20:36 UTC, rtitle commented
Automation tests should exercise this

2019-06-12 20:43 UTC, MatthewBemis commented
test failure was: org.broadinstitute.dsde.workbench.leonardo.notebooks.NotebookRKernelSpec.Leonardo notebooks should be able to install new R packages


```Error Message
"Installing package into ‘/usr/local/lib/R/site-library’&#010;(as ‘lib’ is unspecified)&#010;Warning message in install.packages("httr"):&#010;“'lib = "/usr/local/lib/R/site-library"' is not writable”" did not include substring "/home/jupyter-user/.rpackages"
Stacktrace
      org.scalatest.exceptions.TestFailedException: "Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning message in install.packages("httr"):
“'lib = "/usr/local/lib/R/site-library"' is not writable”" did not include substring "/home/jupyter-user/.rpackages"
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
      at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
      at org.broadinstitute.dsde.workbench.leonardo.notebooks.NotebookRKernelSpec.$anonfun$new$10(NotebookRKernelSpec.scala:76)
      at org.broadinstitute.dsde.workbench.leonardo.notebooks.NotebookTestUtils.$anonfun$withNewNotebook$5(NotebookTestUtils.scala:94)
      at org.broadinstitute.dsde.workbench.leonardo.notebooks.NotebooksListPage.$anonfun$withNewNotebook$2(NotebooksListPage.scala:75)
      at scala.util.Try$.apply(Try.scala:213)
      at org.broadinstitute.dsde.workbench.leonardo.notebooks.NotebooksListPage.withNewNotebook(NotebooksListPage.scala:75)
      at org.broadinstitute.dsde.workbench.leonardo.notebooks.NotebookTestUtils.$anonfun$withNewNotebook$4(NotebookTestUtils.scala:93)
      at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
      at scala.util.Success.$anonfun$map$1(Try.scala:255)
      at scala.util.Success.map(Try.scala:213)
      at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
      at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
      at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
      at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
      at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
      at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
      at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
      at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
      at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)```

2019-06-13 14:56 UTC, rtitle requested changes
The test is probably failing because we have this in the Dockerfile:
```
 && mkdir -p /home/jupyter-user/.rpackages \
 && echo "R_LIBS=/home/jupyter-user/.rpackages" > /home/jupyter-user/.Renviron \
```
and mounting `/work` to `/home/jupyter-user` is wiping out the directory. Maybe we could mount it to `/home/jupyter-user/work` or something.

2019-06-14 20:42 UTC, jmthibault79 approved these changes

2019-06-17 12:39 UTC, calbach commented
OK, this approach passed the tests. However, it cannot be merged as-is.

AoU and Terra UI both specify localization paths of `~/filename`. This means they would break if we pushed this. Here is what I suggest:

- I update this PR so that the notebooks_dir override only happens if USE_WELDER=1
- When moving to the Welder localization API - Terra/AoU update to use local paths rather than home-directory relative paths.

2019-06-17 14:22 UTC, rtitle approved these changes
LGTM

2019-06-18 14:49 UTC, MatthewBemis commented
:+1: looks good to me, merging...

2019-06-18 14:49 UTC, merged